name: is_first_run_plus
description: A simple package to check if it is the first time the app runs.
version: 1.1.0
repository: https://github.com/tijee/flutter_is_first_run_plus

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: