name: is_first_run_plus
description: A simple package to check if it is the first time the app runs.
version: 1.2.1
repository: https://github.com/tijee/flutter_is_first_run_plus

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  package_info_plus: '>=4.2.0 <8.1.1'
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: